### ISSUE TITLE
a few typos

### ISSUE THREAD

**Issue by DataBranner** [vzhz/scrabble_cheater#2]
1. README specifies "8-letter rack" but code returns `Please rerun command and seven-letter rack to play.` when I pass it an eight-letter rack.
2. Typo in "For the maxium points", in program output.
3. Typo in README: `python scrabble_cheater.py`, but program is called `scrabble-cheater.py`.

**Comment by vzhz** [comment]
Thank you, @DataBranner !  Finally getting to this so I feature on my new webpage!  Whooo!
