### ISSUE TITLE
"is" vs ==

### ISSUE THREAD

**Issue by vzhz** [vzhz/scrabble_cheater#6]
Don't use `var is False`. The `is` operator is meant to indicate identity, not equivalence. The `==` operator is meant for equivalence (it's like .equals() in Java as opposed to '==='). You should really only use the `is` operator for comparing to None, which is a singleton in the Python language specification. False and True are not singletons. In Python 2, you can actually assign to True and False! It's much more Pythonic to just say "if not var." As always, see PEP8 (under "Don't compare boolean values to True or False using =="). Here's some reading on how `is` works in Python (and why you should generally avoid it).
http://blog.lerner.co.il/why-you-should-almost-never-use-is-in-python/

**Comment by DavidCain** [comment]
Just a quick heads up that you actually reverted back to `is False` on this commit: https://github.com/vzhz/scrabble_cheater/commit/4969fa4589c5c6094457be99e5d975ed14571ab1
